---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:6.1.3"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:6.1.3"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OpenTelemetry collector"
  org.opencontainers.image.description: "The OpenTelemetry collector packaged for use with HomeAssistant"
  org.opencontainers.image.source: "https://github.com/cedricziel/ha-addon-opentelemetry-collector"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  base_image: mail@cedric-ziel.com
  signer: mail@cedric-ziel.com
